### ISSUE TITLE
Immediate Shutdown

### ISSUE THREAD

**Issue by OukilIl** [FanTranslatorsInternational/Kuriimu2#135]
Kurrimu immediately shutsdown when I open it, the icon appears for a second then disappears.
I'm using Manjaro.

Console:
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gtk.Widget.DrawnSignalCallback(IntPtr inst, IntPtr arg0, IntPtr gch)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at Gtk.Widget.DrawnSignalCallback(IntPtr inst, IntPtr arg0, IntPtr gch)
   at Gtk.Application.Run()
   at Eto.GtkSharp.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at Kuriimu2.EtoForms.Gtk.MainClass.Main(String[] args)

the log file is empty.

**Comment by onepiecefreak3** [comment]
Which version of Kuriimu2 do you use?

**Comment by OukilIl** [comment]
The latest version.
The linux one I'm not using wine with with the windows version

**Comment by onepiecefreak3** [comment]
The question was more intended to get a version number.

**Comment by OukilIl** [comment]
> The question was more intended to get a version number.

Oops, its 1.2.0

**Comment by onepiecefreak3** [comment]
The release version I suppose, not the newest dev version?

**Comment by OukilIl** [comment]
> The release version I suppose, not the newest dev version?

no, I'll try that one

**Comment by OukilIl** [comment]
It's working great.
time to close the issue I guess? xd
