### ISSUE TITLE
Application running into unhandled exceptions when extracting/exporting files

### ISSUE THREAD

**Issue by OnionPlus** [FanTranslatorsInternational/Kuriimu2#261]
**Bug Details:**
This is a bug I've encountered in every game I've opened with the program (which were NDS and 3DS titles), with any file at all. Upon clicking to extract or export something, I get two errors at once that state: "An unhandled exception occurred. Refer to the log for more details. The application will be closed." When referring to the log, it reads the following:

"2022-08-29 17:34:51.462 -06:00 [FTL] An unhandled exception occurred.
System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Kuriimu2.EtoForms.Forms.Formats.ImageForm.ExportPng()
   at Kuriimu2.EtoForms.Forms.Formats.ImageForm.ExportCommand_Executed(Object sender, EventArgs e)
   at Eto.Forms.Command.OnExecuted(EventArgs e)
   at Eto.Forms.Command.Execute()
   at Kuriimu2.EtoForms.Controls.ButtonToolStripItem.ButtonToolStripItem_MouseUp(Object sender, MouseEventArgs e)
   at Eto.PropertyStore.TriggerEvent[T](Object key, Object sender, T args)
   at Eto.Forms.Control.OnMouseUp(MouseEventArgs e)
   at Eto.Forms.Control.Callback.OnMouseUp(Control widget, MouseEventArgs e)
   at Eto.Wpf.Forms.WpfFrameworkElement`3.HandleMouseUp(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)"

I'm no programmer so I'm not entirely sure what most of the above means, but all I know is that this is a relatively new problem for me, as I've used Kuriimu2 before and never had any issues with extracting/exporting until now. I tried deleting the program and re-downloading it, which worked the last time I had the issue, but unfortunately that no longer fixes it. I haven't made any changes to my computer outside of installing regular Windows updates either, if that could be doing anything.

**Comment by daoresaoru** [comment]
Hello! Experiencing the same now, and nobody among my friends knows the solution to this problem. Have you already handled this?
