### ISSUE TITLE
Error on update kuriimu2 tool

### ISSUE THREAD

**Issue by dangvh5** [FanTranslatorsInternational/Kuriimu2#321]
**Game Name:**  
**Console:**  
**Format extension(s):**  
**Type:** [ text | image | archive | font ]

**Bug details:**
I try to update kuriimu2 tool, by include developer build in the setting tab, but it giving me unhandled exception, as written in the log file:
2024-03-22 22:15:38.837 +07:00 [FTL] An unhandled exception occurred.
System.InvalidOperationException: Cannot set Visibility or call Show, ShowDialog, or WindowInteropHelper.EnsureHandle after a Window has closed.
   at System.Windows.Window.VerifyCanShow()
   at System.Windows.Window.Show()
   at Eto.Wpf.Forms.FormHandler.Show()
   at Eto.Forms.Form.Show()
   at Eto.Forms.Application.<>c__DisplayClass53_0.<Run>b__0(Object sender, EventArgs e)
   at Eto.PropertyStore.TriggerEvent[T](Object key, Object sender, T args)
   at Eto.Forms.Application.OnInitialized(EventArgs e)
   at Eto.Forms.Application.Callback.OnInitialized(Application widget, EventArgs e)
   at Eto.Wpf.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at Kuriimu2.EtoForms.Wpf.MainClass.Main(String[] args)
[details]

**Comment by InfiniteParallel** [comment]
Same for me, is there a known way to solve this issue?

**Comment by InfiniteParallel** [comment]
You can find the correct link for the latest Dev build here:

https://github.com/FanTranslatorsInternational/Kuriimu2/issues/331
